version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db-server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  sc-api-getaway:
    build: ./sc-api-getaway
    container_name: api-gateway
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://root:secret@localhost:5433/sc_db?sslmode=disable
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build: ./sc-api-getaway
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: