version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db-server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  sc-auth:
    build:
      context: .
      dockerfile: sc-auth/Dockerfile
    container_name: sc-auth
    depends_on:
      - postgres
    environment:
      SERVER_PORT: "50051"
      DB_SOURCE: postgresql://root:secret@postgres:5432/sc_db?sslmode=disable
    ports:
      - "50051:50051"
    networks:
      - backend

  sc-api-getaway:
    build:
      context: .
      dockerfile: sc-api-getaway/Dockerfile
    container_name: api-gateway
    depends_on:
      - postgres
      - sc-auth
    environment:
      SERVER_PORT: "8000"
      DB_SOURCE: postgresql://root:secret@postgres:5432/sc_db?sslmode=disable
      GRPC_AUTH_PORT: sc-auth:50051
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
