version: '3.8'

services:
  sc-database:
    build:
      context: ./postgres
      dockerfile: sc-database.Dockerfile
    container_name: sc-database
    env_file:
      - ./postgres/.env.db
    ports:
      - "5432:5432"
    networks:
      - backend

  sc-api-getaway:
    build: ./sc-api-getaway
    container_name: sc-api-gateway
    depends_on:
      - sc-database
    environment:
      - DATABASE_URL=postgresql://root:secret@postgresql:5432/sc_db?sslmode=disable
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build: ./sc-api-getaway
    container_name: sc-nginx
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: