host: localhost:8010
info:
  contact:
    email: alex.karadyaur@outlook.com
  description: API for managing user authentication and authorization.
  license:
    name: MIT
    url: https://github.com/karadyauran/soul-connect/blob/main/LICENSE
  title: Authentication gRPC AuthServer
  version: 0.1.0
paths: {}
swagger: "2.0"
